### ISSUE TITLE
Model signature changed

### ISSUE THREAD

**Issue by schmunk42** [dektrium/yii2-user#223]
I noticed that model classes (since 0.9?) do have I different signature than standard Yii2 model classes.

Why do they require a `Finder` as the primary parameter? I think it's not a good practice to change the constructor signature of a class unless absolutely necessary. Can't this simply be done with static call and/or a property?

And if it's required for a reason I do not see at the moment, why not use it as a second param?

Related to: https://github.com/dektrium/yii2-user/issues/212

**Comment by dmeroff** [comment]
From version 0.9.0 Yii2-user uses dependency injection container, so all controllers', models' and components' dependencies [are resolved automatically](https://github.com/yiisoft/yii2/blob/master/docs/guide/concept-di-container.md#resolving-dependencies-).

The order of constructors' arguments does not really matter, they will be resolved correctly. The only reason why it is done in that way is that documentation provides such example, where dependencies go before config argument.

I dont's see any problems with overriding constructors in overriden classes. Base model class does not have any dependencies, and that is why its' constructor has only config param. But the child classes have dependencies on other classes. So we are adding new arguments to constructor's signature. By the way, this can be discussed. If you can provide any significant reasons why it is a problem, code can be refactored to solve it.

**Comment by schmunk42** [comment]
From the docs:

> You can declare the dependency through a constructor parameter and let the DI container to resolve it for you.

But why do you even need it in the constructors? 
Why can't you declare the properties as `public` and use DI to define the `Finder`, ... in your module or application config if needed?

Like so:
```
    /** @var Finder */
    public $finder;

    /**
     * @param Finder $finder
     * @param array $config
     */
    public function __construct($config = [])
    {
        $this->module = \Yii::$app->getModule('user');
        parent::__construct($config);
    }
```    

```    
    \Yii::$container->set(LoginForm::className(), ['finder'=>...])
```

**Comment by dmeroff** [comment]
Of course it can be done in that way. But it makes us to manually configure each class' dependencies. However constructor injection allows to leave dependency configuration to yii. 
Moreover, I prefer constructor injection because in that case we already know that dependency injected and it is correctly typed, but in case of setter/property injection we should check if dependency has already been injected or not.
So I still don't see any problem with constructor dependency injection. It is very common practice.

**Comment by schmunk42** [comment]
I am not very proficient in DI, I stumbled upon this because I had to [change my admin user setup](https://github.com/phundament/app/commit/9d104a788c721add1197928e94c84ea5a2ea518e) after upgrading to 0.9.

I'd have expected to see additional optional parameters for DI, especially for classes derived from commonly used Yii classes.
But now the from-model classes form `yii2-user` all take different parameters `$finder`, `$mailer`, `$config` in various combinations.

It looks overly complicated to me, but as mentioned before, I may not see the full picture.
But these are just my 2 cents, feel free to close the issue.

**Comment by dmeroff** [comment]
`all take different parameters $finder, $mailer, $config in various combinations.`
That is why constructor injection used. In order to make yii inject them automatically. We don't care about how they injected and where are they getting from. We just use `Yii::createObject()` or `Yii::$container->get()` in order to make yii build object automatically.
