### ISSUE TITLE
After the logon, there's an database issue

### ISSUE THREAD

**Issue by jethroredblu** [dektrium/yii2-user#234]
Hi,
sorry, but I've an issue after logon on yii2-advanced.
I configured as indicated on your documentation but there's the problem:
"
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause'
The SQL being executed was: SELECT * FROM `user` WHERE (`id`=1) AND (`status`=10)
Error Info: Array
(    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'status' in 'where clause'
)
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause'
in C:\xampp\htdocs\advanced\vendor\yiisoft\yii2\db\Command.php at line 821

I'm using Xampp for development.
YII2-advanced and Yii2-User are installed with composer.
Step that I do:
- Installed Yii2-advanced and yii2-user with composer
- done init command
- configured DB and email setting in mail-local.php
- Put the followind code in mail-local.php
	    'modules' => [
             'user' => [
            'class' => 'dektrium\user\Module',
            'enableUnconfirmedLogin' => true,
            'confirmWithin' => 21600,
            'cost' => 12,
            'admins' => ['admin']
             ],
		],

- Done with successfull  the creation of new user with action /user/registration/register
- When I try the action /user/security/login, I've the error SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause' ....

Where is the problem? Can you help me?
Thank you in advanced.

**Comment by dmeroff** [comment]
Please, make sure that you have no configuration of `user` component in your config files. In advanced template it is located [here](https://github.com/yiisoft/yii2-app-advanced/blob/master/frontend/config/main.php#L15) by default.

**Comment by dmeroff** [comment]
@jethroredblu has the problem been solved with my answer?

**Comment by aleoy** [comment]
I had the same issue. Solved it by accessing the propper login URL => user/security/login
Do not change the frontend and backend settings.

On common/config/main.php set the module configuration so that both frontend and backend can use the same data:
...
'modules' => [
 ...
      'user' => [
        'class' => 'dektrium\user\Module',
        'enableUnconfirmedLogin' => true,
        'confirmWithin' => 21600,
        'cost' => 12,
        'admins' => ['admin']
      ],
...
    ],

If you want to customize the routes there are many ways to go about it:

1 - change the views links in order to point to the URLs specified by the model

2 - change the prexisting controllers and redirect to the URLs specified by the model

3 - change the configuration for the UrlManager where you can specify a rule  to override controller/index

Choose whatever suits you best, although I prefer changing the view and removing the pre-existing actions in the SiteController

**Comment by mustafaunesi** [comment]
Delete this code and ok.
/backend/config/main.php 

'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
        ],
