### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by phwhite** [dektrium/yii2-user#241]
It would be nice to use MongoDB as the backend database instead of SQL.  Are there currently any plans to implement this?

**Comment by dmeroff** [comment]
No there are no plans for implementing this, because I've never worked with MongoDB, so it will take time to understand the basics of MongoDB, and there are some features and enhancements that should be done firstly.

By the way, you are very welcome to send a pull-request that provides MongoDB support to Yii2-user.

**Comment by phwhite** [comment]
Thanks for the response.  I would like to implement the mongodb support
myself, however I'm concerned about future updates.  If I do implement
mongodb support, is this something you would be interested in accepting
back if implemented properly?

Thanks
Paul

**Comment by dmeroff** [comment]
@phwhite my english is not really good, so I may misunderstood you. Under `accepting back` do you mean implementing any other features after implementing mongo db support?

**Comment by phwhite** [comment]
Sorry, let me try to word it better

I would like to contribute code to your project adding mongodb support.  I
will add the support and submit the changes back to you for review if that
is OK

Thanks for your time
Paul

**Comment by vavoluk** [comment]
Is there any progress in MongoDB implementation?
