### ISSUE TITLE
Make rule for username configurable

### ISSUE THREAD

**Issue by xerxes87** [dektrium/yii2-user#251]
In usernames, no dashes or points are allowed
Would be great, if the regex would be configurable through the configuration, because it is defined within the user model, the RegistrationForm and the SettingsForm.

**Comment by dmeroff** [comment]
I don't think that we should introduce new module's configuration options, because you need to configure username pattern, other user need to configure password length, other user need to configure something else. If we will add new configuration options for each user request, there will be huge number of options that will confuse developers.
I agree that validation rules should be configurable, but at the moment I don't see the way to do this.
