### ISSUE TITLE
Custom user image and opportunity to unplug gravatar

### ISSUE THREAD

**Issue by vladim1** [dektrium/yii2-user#272]
I don't need gravatar functionality on my web-site. Is it possible to unplug it? It's very useful feature, it should be used on some websites, but it's not needed everywhere.

IMHO, as the enhancement, the module should show the image the following way:
- show uploaded image, if it was uploaded before (as I can see uploading images is going to be implemented)
- show social network avatar, if no other image was uploaded and user is entered via social network
- show site custom default image for users, that has logged in on the web-site (not via social networks), but haven't uploaded images yes.
PS: Is new release is going to be published? Milestones tab shows, that is was planned 8 days ago.
PPS: very good extension. It can become even better and perfect for all yii2 web-sites if it'll have uploading images functionality and more flexibility with icons.

**Comment by dmeroff** [comment]
You can override profile settings form and remove gravatar field from there. By the way, you will also need to adjust default scenario of Profile model, to prevent mass-assignment for gravatar field.

I'm thinking to adjust profile picture as follows:

1) Remove `gravatar_email` field and use user's email address to generate gravatar hash.
2) Add special method to profile model, that will return profile picture url
3) If user uploaded image, then that method will return it's url, otherwise gravatar url.

PS. New release is coming in a few days.

**Comment by vladim1** [comment]
I would suggest to implement the opportunity to turn on and off gravatar image in the configuration. So (in case if gravatar is turned off) if user hasn't uploaded image yet, the default image will be shown. The default image could be specified in the configuration also. This approach gives a huge flexibility.

**Comment by dmeroff** [comment]
Of course, I can add configuration options for every single line of code (you need to disable gravatar, someone needs to disable something else). But this options will provide only complication for me as a developer, and for you as an end user. IMHO, profile model provides needed flexibility, because you may override it and implement whatever you need.
