### ISSUE TITLE
User table should have "role" field

### ISSUE THREAD

**Issue by invaderhd** [dektrium/yii2-user#296]
I think user table should have for default the "role" field, is someone don't want to use there are no problem, but this field is very useful to implement rbac.

At this point is not easy create a new field and add it to yii2-user, today I spend hours to add the role field, for this I need to override models and views. Some months ago I can implement RBAC in minutes now since you remove the role field it's a hard to get RBAC.

Even people that not use RBAC can use the role to create different types of users.

**Comment by dmeroff** [comment]
No, I don't think, that `role` field should exist in user model by default. Using this field for RBAC is application-specific and provides unneeded confusion, because standard yii2 rbac system works on the other way (it uses separate table for storing auth assignments).

BTW what problems did you meet, when you were adding new field to user model? I can mention that in docs, because at the moment I don't understand how it can take hours to do such thing?

**Comment by invaderhd** [comment]
You can put on documentation an example how to add a field to user table and how to add a field do profile table.

I exaggerate a little bit, but I spend some time to get the role field in the user table:
1 - create migration
2 - migrate to create the role field on user table
3 - override user model to add the role field (attributeLabels, rules, beforeSave, scenarios) 
4 - override the views to put the role field on the edit form.

I'dont work everyday with yii and take me some time to do this, next time will be fast but an example who to add field on user and profile table will help alot of people.
