### ISSUE TITLE
Migration Error: Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by Lomejook** [dektrium/yii2-user#543]
I get this error when I applied the migration. (Sorry for bad english)

*** applying m140403_174025_create_account_table
    > create table {{%account}} ... done (time: 0.120s)
    > create unique index account_unique on {{%account}} (provider,client_id) ...Exception 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
The SQL being executed was: ALTER TABLE `account` ADD UNIQUE INDEX `account_unique` (`provider`, `client_id`)'

in /Users/username/Documents/advanced/vendor/yiisoft/yii2/db/Schema.php:628

Error Info:
Array
(
    [0] => 42000
    [1] => 1071
    [2] => Specified key was too long; max key length is 1000 bytes
)

**Comment by nikbas** [comment]
This is MySQL issue.

Which database version and collation are you using?

I got similar error when I applied these migrations on database with `utf8mb4` collation because it uses 4 bytes per character and therefore it rejects unique indexes on varchar(255) columns because 4*255 > 1000 (767 for InnoDB). Switching to `utf8` collation will make it work since it uses 3 bytes per character.

**Comment by Lomejook** [comment]
Solved:
I changed mysql engine default to Innodb
