### ISSUE TITLE
Returning to previous action after logon

### ISSUE THREAD

**Issue by dbd5** [dektrium/yii2-user#651]
Hi Dmitry & All,

Sometimes one encounters a situation where a user is not logged in and starts a sequence of actions one of which is allowed for only logged in users so we redirect him to /user/security/login. However, after login he is taken to site/index.

For usability reasons, Is there a way to return user to exactly where he was in the sequence of actions like the following diagram instead of sending him to site/index?

STEP1 -> STEP2 -> STEP3 -> < LOGGEDIN?YES:LOGIN > STEP4

Regards,

Adam

**Comment by blackwolfinsane** [comment]
Hi.

I think that could be done with [yii\helpers\Url::remember() and yii\helpers\Url::previous()](http://www.yiiframework.com/doc-2.0/guide-helper-url.html#remember-urls)

**Comment by dmeroff** [comment]
Actually, it is already working this way. Yii2-user uses `goBack` method of `yii\web\Controller` which does exactly what you just described.

You can check it out on demo site:
1) Log out
2) For example, go to settings page - http://yii2-user.dmeroff.ru/user/settings/profile
3) You will be redirected to the login page since settings page is only allowed for logged in users
4) You log in and get instantly redirected back to settings page.
