### ISSUE TITLE
Replace jQuery UI datepicker with Bootstrap datepicker

### ISSUE THREAD

**Issue by michael-vostrikov** [dektrium/yii2-user#705]
Could you please replace jQuery UI datepicker with "2amigos/yii2-date-picker-widget" or "kartik-v/yii2-widget-datepicker"? It's not necessary to pull the whole jQuery UI library (4+ MB) just for one datepicker)

**Comment by jmbb** [comment]
Perhaps you should use the minimised version. It's only 63.5 KB

**Comment by michael-vostrikov** [comment]
No, I mean that "dektrium/yii2-user" requires "yiisoft/yii2-jui", and
"yiisoft/yii2-jui" requires "bower-asset/jquery-ui", which size is 4.7MB.

2016-06-11 21:47 GMT+05:00 Johan <notifications@github.com>:

**Comment by thiagotalma** [comment]
--prefer-dist?

**Comment by michael-vostrikov** [comment]
This option is not related to bower package size.

**Comment by dmeroff** [comment]
I agree. I'm planning to get rid of jui dependency, since it does not make much sence. I think we don't need datepicker dependency at all, because not all projects use default user manager panel, and if someone wants to have datepicker, he can just override view and use datepicker on his own choice.

**Comment by dmeroff** [comment]
Done!
