### ISSUE TITLE
redirect to home

### ISSUE THREAD

**Issue by gb5256** [dektrium/yii2-user#722]
Why is the login action redirecting me to the home instead of the last visited page?

Any ideas?

PS: I read here in some older issues that this should work, but not for me.
Can somebody please check that this is supposed to work right now?

**Comment by dmeroff** [comment]
Do you mean that you are not redirected back to the page where access for guests is forbidden after loggin in? Or you mean that if you click login link from any page and after logging in you're not redirected back? If the latter, then there is nothing wrong, because you're not supposed to be redirected back. If the former, then I don't know really, I've never experienced such issue.

**Comment by gb5256** [comment]
You are right. I tought that it will return me to the page where I clicked on the login button.
I am now storing the referer in a session var for this purpose.
Thanks for your help.
