### ISSUE TITLE
Argument 3 passed to dektrium\user\controllers\AdminController::__construct() 

### ISSUE THREAD

**Issue by RGTimothy** [dektrium/yii2-user#758]
I went to override models, views, and controllers. I did your step on your documentation but then I get this error : **Argument 3 passed to dektrium\user\controllers\AdminController::__construct() must be an instance of dektrium\user\Finder, array given, called in C:\wamp64\www\appname\controllers\user\AdminController.php on line 140 and defined**

Please help, thanks!

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the framework, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
