### ISSUE TITLE
How to use login with Web Service?

### ISSUE THREAD

**Issue by RonEskinder** [dektrium/yii2-user#786]
I need to create a WS that returns the user data, in Yii2-basic this is done with the AuthController and calling `$user = \app\models\User::findByUsername($username);` and then `if ($user->validatePassword($password)) {`

How can i make this happen with this library

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
