### ISSUE TITLE
How to leave just the registration?

### ISSUE THREAD

**Issue by ankkk** [dektrium/yii2-user#787]
Greetings, wanted to ask how to make unavailable to the user and the URL of the page, for example these:
- /user/registration/register
- /user/registration/resend
- /user/registration/confirm
- /user/security/login
- /user/recovery/request
- /user/recovery/reset
- /user/settings/profile
- /user/settings/account
- /user/settings/networks
- /user/profile/show
- /user/admin/index
- /user/login

**Comment by philippfrenzel** [comment]
Rbac?!;) Access Filter and you define who can access them...

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
