### ISSUE TITLE
action user/admin/index redirects to site/login

### ISSUE THREAD

**Issue by naeemtawwos** [dektrium/yii2-user#793]
when i request for action user/admin/index i get redirected to site/login action

| Q | A |
| --- | --- |
| Yii2 |  |
| Yii2-user version |  |
| PHP version |  |

**Comment by tsdogs** [comment]
You probably miss some configuration. Recheck you have enabled the module.
The module bootstrap (which should be included with composer) should take care to set the
correct settings.

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
