### ISSUE TITLE
Registration with Google/Facebook 

### ISSUE THREAD

**Issue by harlangray** [dektrium/yii2-user#797]
I have enabled authentication with Google and Facebook. I can login with Google and Facebook, but cannot register a new user with social authentication. It looks like it was possible in previous versions of yii2 user according to this. (https://code.tutsplus.com/tutorials/how-to-program-with-yii2-google-authentication--cms-24987) However the registration form does not have the links anymore. Isn't this possible now?

**Comment by markusvisse** [comment]
Bump. Same here. I followed your documentation but nothing changed on login/register form. Social networks tab is present in setting tho.

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
