### ISSUE TITLE
How to disable email during registration?

### ISSUE THREAD

**Issue by ankkk** [dektrium/yii2-user#811]
I want disable the check for email that a user could log in via a social network without email. How can I do that?
![Auth](http://i.imgur.com/aZ5m896.png)

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
