### ISSUE TITLE
404 error on social login 

### ISSUE THREAD

**Issue by josemonmaliakal** [dektrium/yii2-user#813]
Configured the social login using the guide https://github.com/dektrium/yii2-user/blob/master/docs/social-auth.md, but the login page is with 404 error 

public_html/user/security/auth?authclient=facebook

I have configured the website for frontend and backend seperately, it is working on backend but not in frontend 
any suggestion ?

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
