### ISSUE TITLE
Backend Auth - after login and redirect session destroy.

### ISSUE THREAD

**Issue by ApXaHgheJI** [dektrium/yii2-user#817]
### What steps will reproduce the problem?
configure the Advanced, install yii2-user from Advanced quide.
from backend config remove the default session row with name
`     'session' => [
            // this is the name of the session cookie used for login on the frontend
            'name' => 'advanced-backend',
        ],`

## What is the expected result?

if you remove this row - the user will get login, but after refresh the SESSION will be destroyed.

Complete config must be like this:

`  'session' => [
            'name' => 'BACKENDSESSID',
            'cookieParams' => [
                'httpOnly' => true,
                'path' => '/admin',
            ],
        ],
        'session' => [
            // this is the name of the session cookie used for login on the frontend
            'name' => 'advanced-backend',
        ],
`

In this case the authorisation will work.
This issue is just for info.

Best regards.

### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      |
| Yii2-user version |
| PHP version       |

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
