### ISSUE TITLE
How to use yii2-user with Advance Form (Backend use another admin table to login)

### ISSUE THREAD

**Issue by samsoft00** [dektrium/yii2-user#848]
Please how can i make backend login to make use of 'admin' database table from yii2-user configuration, i have try all possible best but nothing is working. Please help.

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
